   databases:
      - name: rails-mister-cocktail
        databaseName: rails_mister_cocktail_production
        user: rails_mister_cocktail_production_user



   services:
      - type: web
        name: rails-mister-cocktail
        env: ruby
        buildCommand: "./bin/render-build.sh"
        startCommand: " bundle exec rails s"
        envVars:
          - key: DATABASE_URL
            fromDatabase:
              name: rails-mister-cocktail_production
              property: connectionString
          - key: RAILS_MASTER_KEY
            sync: false
